{
  pkgs,
  config,
  ...
}: let
  browser = "${pkgs.google-chrome}/bin/google-chrome-stable";
  terminal = "${config.programs.wezterm.package}/bin/wezterm";
  waybar = "${pkgs.waybar}/bin/waybar";
  wofi = "${pkgs.wofi}/bin/wofi";
  wob = "${pkgs.wob}/bin/wob";
  wpctl = "${pkgs.wireplumber}/bin/wpctl";
  playerctl = "${pkgs.playerctl}/bin/playerctl";
  brightnessctl = "${pkgs.brightnessctl}/bin/brightnessctl";
  grim = "${pkgs.grim}/bin/grim";
  slurp = "${pkgs.slurp}/bin/slurp";
  swappy = "${pkgs.swappy}/bin/swappy";
  notify-send = "${pkgs.libnotify}/bin/notify-send";
  emote = "${pkgs.emote}/bin/emote";
  hyprctl = "${pkgs.hyprland}/bin/hyprctl";
  systemctl = "${pkgs.systemd}/bin/systemctl";
  awk = "${pkgs.gawk}/bin/awk";
  # wl-clip-persist = lib.getExe pkgs.wl-clip-persist;
  blueman-applet = "${pkgs.blueman}/bin/blueman-applet";
  hyprpaper = "${pkgs.hyprpaper}/bin/hyprpaper";
in let
  getVolumeScript = pkgs.writeShellScript "get-volume-script" ''
    ans=$(${wpctl} get-volume @DEFAULT_AUDIO_SINK@)
    if echo "$ans" | grep -q MUTED; then
      echo 0
    else
      echo "$ans" | ${awk} -F': ' '{printf "%.0f\n", $2*100}'
    fi
  '';

  # wofi --show drun | xargs -Ioutput hyprctl dispatch exec output
  wofiWithFilter = pkgs.writeShellScript "wofi-with-filter" ''
    res=$(${wofi} --show drun)
    # filter=("Telegram --")
    filter=()
    for name in "''${filter[@]}"; do
      if [ "$res" = "$name" ]; then
        exit
      fi
    done
    ${hyprctl} dispatch "hl.dsp.exec_cmd(\"$res\")"
  '';
  volumePt = "0.04";
in let
  hyprlandSettings = ''
    -- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

    local altMod = "ALT"
    local mainMod = "SUPER"
    local shiftMod = "SUPER + SHIFT"

    hl.bind(mainMod .. " + q", hl.dsp.window.close())
    hl.bind(mainMod .. " + m", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
    hl.bind(mainMod .. " + f", hl.dsp.window.float({ action = "toggle" }))
    hl.bind(mainMod .. " + p", hl.dsp.window.pin())
    hl.bind(mainMod .. " + d", hl.dsp.exec_cmd("${wofiWithFilter}"))
    hl.bind(shiftMod .. " + d", hl.dsp.exec_cmd("${wofi} --show run"))
    hl.bind(mainMod .. " + t", hl.dsp.exec_cmd("${terminal}"))
    hl.bind(mainMod .. " + b", hl.dsp.exec_cmd("${browser}"))
    hl.bind(mainMod .. " + escape", hl.dsp.exec_cmd("~/.config/wofi/power-menu.sh"))
    hl.bind(shiftMod .. " + escape", hl.dsp.exit())
    hl.bind(mainMod .. " + code:60", hl.dsp.exec_cmd("${emote}"))
    hl.bind(altMod .. " + Tab", hl.dsp.focus({ last = true }))
    hl.bind(mainMod .. " + 0", hl.dsp.workspace.toggle_special(""))
    hl.bind(shiftMod .. " + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
    hl.bind(shiftMod .. " + 0", hl.dsp.window.move({ workspace = "special", follow = false }))
    hl.bind(shiftMod .. " + right", hl.dsp.window.move({ workspace = "+1" }))
    hl.bind(shiftMod .. " + left", hl.dsp.window.move({ workspace = -1 }))
    hl.bind(mainMod .. " + h", hl.dsp.focus({ workspace = -1 }))
    hl.bind(mainMod .. " + l", hl.dsp.focus({ workspace = "+1" }))
    hl.bind(shiftMod .. " + h", hl.dsp.focus({ direction = "left" }))
    hl.bind(shiftMod .. " + l", hl.dsp.focus({ direction = "right" }))
    hl.bind(shiftMod .. " + k", hl.dsp.focus({ direction = "up" }))
    hl.bind(shiftMod .. " + j", hl.dsp.focus({ direction = "down" }))

    hl.bind("XF86AudioMute", hl.dsp.exec_cmd("${wpctl} set-mute @DEFAULT_AUDIO_SINK@ toggle && ${getVolumeScript} > $WOBSOCK"))
    hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("${brightnessctl} s 5%- && ${brightnessctl} -m | cut -d ',' -f 4 | cut -d '%' -f 1 > $WOBSOCK"))
    hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("${brightnessctl} s +5% && ${brightnessctl} -m | cut -d ',' -f 4 | cut -d '%' -f 1 > $WOBSOCK"))
    hl.bind("XF86AudioNext", hl.dsp.exec_cmd("${playerctl} next"))
    hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("${playerctl} previous"))
    hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("${playerctl} play-pause"))
    hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("${wpctl} set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ ${volumePt}- && ${getVolumeScript} > $WOBSOCK"), { repeating = true })
    hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("${wpctl} set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ ${volumePt}+ && ${getVolumeScript} > $WOBSOCK"), { repeating = true })

    hl.bind("Print", hl.dsp.exec_cmd("${grim} -g \"$(${slurp})\" - | ${swappy} -f - && ${notify-send} 'Saved to ~/Pictures/Screenshots'"))
    hl.bind(altMod .. " + Print", hl.dsp.exec_cmd("${grim} - | ${swappy} -f - && ${notify-send} 'Saved to ~/Pictures/Screenshots'"))

    hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
    hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
    hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
    hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
    hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
    hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
    hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
    hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
    hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
    hl.bind(shiftMod .. " + 1", hl.dsp.window.move({ workspace = 1 }))
    hl.bind(shiftMod .. " + 2", hl.dsp.window.move({ workspace = 2 }))
    hl.bind(shiftMod .. " + 3", hl.dsp.window.move({ workspace = 3 }))
    hl.bind(shiftMod .. " + 4", hl.dsp.window.move({ workspace = 4 }))
    hl.bind(shiftMod .. " + 5", hl.dsp.window.move({ workspace = 5 }))
    hl.bind(shiftMod .. " + 6", hl.dsp.window.move({ workspace = 6 }))
    hl.bind(shiftMod .. " + 7", hl.dsp.window.move({ workspace = 7 }))
    hl.bind(shiftMod .. " + 8", hl.dsp.window.move({ workspace = 8 }))

    hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
    hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

    hl.env("WOBSOCK", os.getenv("XDG_RUNTIME_DIR").."/wob.sock")
    hl.env("WLR_NO_HARDWARE_CURSORS", "1")

    hl.gesture({
        fingers = 4,
        direction = "horizontal",
        action = "workspace",
    })

    -- TODO: Add script to `hyprctl dispatch moveworkspacetomonitor 2 DP-1` on monitor connection.
    -- TODO: Script to toggle laptop's monitor: https://github.com/hyprwm/Hyprland/issues/2845
    hl.monitor({
        output = "eDP-1",
        mode = "1920x1080@60",
        position = "0x0",
        scale = "1",
    })

    hl.monitor({
        output = "DP-1",
        mode = "2560x1440@60",
        position = "auto-up",
        scale = "1",
    })

    hl.window_rule({
        match = {
            class = "^(jetbrains-idea)(.*)$",
        },
        border_size = 0,
    })

    hl.window_rule({
        match = {
            class = "^(org.telegram.desktop|telegramdesktop)$",
            title = "^(Media viewer)$",
        },
        float = true,
    })

    hl.window_rule({
        match = {
            class = "google-chrome",
        },
        scroll_touchpad = 0.1,
    })

    hl.window_rule({
        match = {
            title = "^()$",
            class = "^(steam)$",
        },
        stay_focused = true,
        -- TODO: manual review — unmapped window rule action: "minsize 1 1"
    })

    hl.window_rule({
        match = {
            title = "^(.*)(NETCONF|NetConf)(.*)$",
        },
        float = false,
    })

    hl.window_rule({
        match = {
            class = "steam_app*",
        },
        -- TODO: manual review — unmapped window rule action: "idleinhibit fullscrean"
    })

    hl.workspace_rule({
        workspace = "1",
        monitor = "DP-1",
        default = true,
    })

    hl.workspace_rule({
        workspace = "2",
        monitor = "DP-1",
    })

    hl.workspace_rule({
        workspace = "3",
        monitor = "DP-1",
    })

    hl.workspace_rule({
        workspace = "9",
        monitor = "eDP-1",
        default = true,
    })

    hl.config({
        animations = {
            enabled = false,
        },
        decoration = {
            rounding = 5,
        },
        dwindle = {
            force_split = 2,
            -- TODO: pseudotile = true,
        },
        ecosystem = {
            no_update_news = true,
        },
        general = {
            gaps_out = 0,
            layout = "dwindle",
        },
        gestures = {
            workspace_swipe_distance = 130,
        },
        input = {
            touchpad = {
                middle_button_emulation = true,
                natural_scroll = true,
                scroll_factor = 0.200000,
                -- TODO: ["tap-to-click"] = true,
            },
            follow_mouse = 2,
            kb_layout = "us,ua",
            kb_options = "grp:win_space_toggle",
            repeat_delay = 220,
            repeat_rate = 25,
            sensitivity = -0.25,
        },
        misc = {
            disable_hyprland_logo = true,
            disable_splash_rendering = true,
            focus_on_activate = true,
        },
        xwayland = {
            force_zero_scaling = true,
        },
    })

    hl.on("hyprland.start", function()
        hl.exec_cmd("${waybar}")
        hl.exec_cmd("${blueman-applet}")
        hl.exec_cmd("${emote}")
        hl.exec_cmd("${hyprpaper}")
        hl.exec_cmd("${hyprctl} setcursor ${config.home.pointerCursor.name} ${toString config.home.pointerCursor.size}")
        hl.exec_cmd("${browser}", { workspace = "1 silent" })
        hl.exec_cmd("${terminal}", { workspace = "2 silent" })
        hl.exec_cmd("${terminal}", { workspace = "9 silent" })
        hl.exec_cmd("rm -f $WOBSOCK && mkfifo $WOBSOCK && tail -f $WOBSOCK | ${wob}")
    end)

  '';
in {
  wayland.windowManager.hyprland = {
    enable = true;
    extraConfig = hyprlandSettings;
    configType = "lua";
    # Window titles: https://github.com/hyprwm/hyprland-plugins/tree/main/hyprbars
    # plugins = with pkgs; [
    # ];
  };

  services = {
    hyprpaper = {
      enable = true;
      settings = {
        splash = false;
        wallpaper = [
          {
            path = "${config.home.sessionVariables.XDG_WALLPAPERS_DIR}/main.jpg";
            monitor = "";
          }
        ];
      };
    };
    # WARN: Not sure if it works after nixpkgs upgrade from 25.11 to 26.05
    hypridle = {
      enable = true;
      settings = {
        general = {
          after_sleep_cmd = "${hyprctl} dispatch dpms on";
        };
        listener = [
          {
            timeout = 600;
            on-timeout = "${hyprctl} dispatch dpms off";
            on-resume = "${hyprctl} dispatch dpms on";
          }
          {
            # TODO: Need to press a key twice after suspend to dpms on.
            # TODO: Make script to lock screen before hibernation.
            timeout = 1800;
            on-timeout = "${systemctl} suspend";
          }
        ];
      };
    };
  };
}
